language: shell
env:
  global:
  - BUILD_NAME="PrimInputActions"
  - UNITYCI_PROJECT_NAME="PrimInputActions"
  
services:
- docker
  
# only run builds on pushes to the master branch
branches:
  only:
  - main

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - chmod +x ./Tools/Travis/docker_test.sh
  - chmod +x ./Tools/Travis/docker_build.sh
  - chmod +x ./Tools/Travis/build.sh
  - chmod +x ./Tools/Travis/before_script.sh
  - chmod +x ./Tools/Travis/test.sh
  - chmod +x ./Tools/DownloadDependencies/*.sh
  - export -f travis_fold
  - (cd Tools/DownloadDependencies/; sh download-dependencies.sh)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull $IMAGE_NAME

jobs:
  include:
  - stage: test
    script: "./Tools/Travis/docker_test.sh"
    env: TEST_PLATFORM=editmode IMAGE_NAME=unityci/editor:ubuntu-2021.1.1f1-linux-il2cpp-0
    addons:
      artifacts:
        s3_region: "eu-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test
    script: "./Tools/Travis/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=unityci/editor:ubuntu-2021.1.1f1-linux-il2cpp-0
    addons:
      artifacts:
        s3_region: "eu-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
